// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: ListsFromUsers.sql

package sqlc

import (
	"context"
)

const addListToUser = `-- name: AddListToUser :one
INSERT INTO "user_to_list" (user_id, list_id)
VALUES ($1, $2) RETURNING list_id, user_id
`

type AddListToUserParams struct {
	UserID int32 `json:"user_id"`
	ListID int32 `json:"list_id"`
}

func (q *Queries) AddListToUser(ctx context.Context, arg AddListToUserParams) (UserToList, error) {
	row := q.db.QueryRowContext(ctx, addListToUser, arg.UserID, arg.ListID)
	var i UserToList
	err := row.Scan(&i.ListID, &i.UserID)
	return i, err
}

const deleteListFromUser = `-- name: DeleteListFromUser :exec
DELETE FROM "user_to_list" where list_id = $1
`

func (q *Queries) DeleteListFromUser(ctx context.Context, listID int32) error {
	_, err := q.db.ExecContext(ctx, deleteListFromUser, listID)
	return err
}
